21 create food page
GSG-FC03/foodk-app pull request #32
Opened 2021-08-07 18:57 UTC by Mosab-Ahmed

2021-08-07 18:58 UTC, Abdelrahman059 commented
Great Job

2021-08-07 18:59 UTC, Abdelrahman059 approved these changes

2021-08-07 19:36 UTC, farahalashi approved these changes

2021-08-07 20:07 UTC, salsabeelomar approved these changes

2021-08-07 20:37 UTC, salsabeelomar requested changes
the is not suitable for iPhone 11 pro max 
the image is too big

2021-08-08 09:18 UTC, farahalashi approved these changes

2021-08-08 10:35 UTC, sara219 approved these changes

2021-08-08 10:35 UTC, merged