edit search style & in html put icon and input in div
GSG-FC03/foodk-app pull request #45
Opened 2021-08-08 20:39 UTC by Mosab-Ahmed

relate #44

2021-08-08 21:03 UTC, salsabeelomar approved these changes

2021-08-08 21:22 UTC, Abdelrahman059 approved these changes

2021-08-09 07:24 UTC, farahalashi approved these changes

2021-08-09 07:42 UTC, Abdelrahman059 requested changes
Search bar is working just on food page, Do it with Drinks Page too

2021-08-09 10:31 UTC, sara219 approved these changes

2021-08-09 10:31 UTC, merged